name: Tests

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install required dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -U .
      - name: Set executable permissions for file on *nix-systems
        if: matrix.os != 'windows-latest'
        run: chmod +x ./functional_tests/megago-test.sh
      - name: Run tests against ${{ matrix.os }}
        run: ./functional_tests/megago-test.sh -p megago -d ./functional_tests/testdata
