name: Uptime

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 * * * *'

jobs:
  api_available:
    runs-on: ubuntu-latest
    steps:
      - name: Install required utilities
        run: |
          sudo apt-get update
          sudo apt-get -y install bc
      - uses: actions/checkout@v2
      - name: Run uptime check
        shell: bash
        run: |
          chmod u+x ./test/uptime/check_api_response.sh
          ./test/uptime/check_api_response.sh
