name: Tests

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install required dependencies on ${{ matrix.os }}
        if: matrix.os != 'windows-latest'
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements-dev.txt
          pip3 install -U .
      - name: Install required dependencies on ${{ matrix.os }}
        if: matrix.os == 'windows-latest'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -U .
      - name: Run tests against ${{ matrix.os }}
        if: matrix.os != 'windows-latest'
        run: python3 functional_tests/megago-test.py -v -p megago -d ./functional_tests/testdata
      - name: Run tests against ${{ matrix.os }}
        if: matrix.os == 'windows-latest'
        run: python functional_tests/megago-test.py -v -p megago -d ./functional_tests/testdata
